package:
  create: 
    set:
      zarf_version: 0.29.0
      k3d_version: 5.5.2
      k3s_version: v1.27.4
      k3s_gpu_image: ghcr.io/runyontr/packages/rancher/k3s:v1.27.2-k3s1-cuda
    max_package_size: "1000000000"
  deploy:
    set:
      approved_registries: "127.0.0.1* | registry1.dso.mil* | registry.dso.mil* | k3d-airgap.localhost* | nvcr.io/nvidia* | docker.io/semitechnologies* | ghcr.io/defenseunicorns* | semitechnologies/* | ghcr.io/runyontr*"
